config/routes.rb
Cwblog::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'tags/:tag', to: 'welcome#index', as: :tag

  root 'welcome#index', :as => :home

  resources :posts

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/post.rb
class Post < ActiveRecord::Base
	attr_accessible :title, :body, :tag_names
  attr_accessor :tag_names
  after_save :assign_tags

  validates :title, presence: true
  validates :body, presence: true
  
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  def self.tagged(name)
    Tag.find_by_name!(name).posts
  end

  def tag_names
    @tag_names || tags.map(&:name).join(' ') 
  end

  private

  def assign_tags
    if @tag_names
      self.tags = @tag_names.split(/\s+/).map do |name|
        Tag.find_or_create_by_name(name.strip)
      end
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  validates :name, presence: true

  has_many :taggings
  has_many :posts, through: :taggings

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :sidebar

  def sidebar
    @archived_posts = Post.find(:all, :id, order: 'created_at DESC').group_by { |post| post.created_at.strftime("%B %Y")}
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:tag]
      @posts = Post.tagged(params[:tag])
    else
      @posts = Post.all
    end
  end
  
  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if params[:tag]
      @posts = Post.tagged(params[:tag])
    else
      @posts = Post.all.order('created_at DESC')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_footer.html.haml
%footer#footer
  %small.copyright
    werk42, Copyright &copy; #{ Date.today.year }

app/views/application/_head.html.haml
%head
  %meta{ :charset => 'utf-8' }/
  %meta{ 'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1' }/

  %title
    == #{ controller.controller_name.titleize } - #{ controller.action_name.titleize }

  %meta{ :name => 'description', :content => '' }/
  %meta{ :name => 'viewport', :content => 'width=device-width' }/

  = render 'stylesheets'
  = javascript_include_tag 'polyfills'

  = csrf_meta_tag

app/views/application/_header.html.haml
%header#header
  %h2=link_to "werk42", home_path

app/views/layouts/application.html.haml
!!! 5
- html_tag :class => 'no-js' do
  = render 'head'

  %body
    = render 'chromeframe'
    = render 'header'
    = render 'flashes'

    = yield

    = render 'footer'

    -# Javascript at the bottom for fast page loading
    = render 'javascripts'

app/views/posts/show.html.haml
.posts-container
  .title= @post.title
  .content= raw @post.body
  .date
    %b published: 
    = @post.created_at.strftime('%d %B, %Y')
  .tag
    %b tags:
    = raw @post.tags.map(&:name).map { |t| link_to t, tag_path(t)}.join(', ')  

=render "welcome/sidebar"

app/views/welcome/_sidebar.html.haml
.sidebar
  .archive-container Archive
  - @archived_posts.each do |month, posts|
    .month= month
    - posts.each do |post|
      .title
        = link_to post.title, post_path(post)

app/views/welcome/index.html.haml
.posts-container
  - @posts.each do |post|
    %li 
      .title= post.title
      .content= raw post.body
      .date
        %b published: 
        = post.created_at.strftime('%d %B, %Y')
      .tag
        %b tags: 
        = raw post.tags.map(&:name).map { |t| link_to t, tag_path(t)}.join(', ')

=render "sidebar"